import pandas as pd

# Define your data as a list of dictionaries
data = [
        {'name': 'Alexis Weathersbee', 'email': 'alexis.weathersbee@theagencyre.com', 'phone': '(909) 231-2230'},
        {'name': 'Amy Havel', 'email': 'amy.havel@theagencyre.com', 'phone': '(718) 764-3852'},
        {'name': 'Andrea Weller', 'email': 'andrea.weller@theagencyre.com', 'phone': '(732) 261-8719'},
        {'name': 'Andrew Cooper', 'email': 'drew@theagencyre.com', 'phone': '(917) 699-3999'},
        {'name': 'Andy Pickerill', 'email': 'andy.pickerill@theagencyre.com', 'phone': '(502) 303-2498'},
        {'name': 'Anna Vlas', 'email': 'annavlas@theagencyre.com', 'phone': '(646) 287-2253'},
        {'name': 'AnneMarie Tamis-Nasello', 'email': 'atamis@theagencyre.com', 'phone': '(917) 292-0010'},
        {'name': 'Ann Marie Fisher', 'email': 'annmarie.fisher@theagencyre.com', 'phone': '(860) 519-8618'},
        {'name': 'Anthony Raimondi', 'email': 'anthony.raimondi@theagencyre.com', 'phone': '(917) 746-7458'},
        {'name': 'Arielle Carraha', 'email': 'arielle@theagencyre.com', 'phone': '(973) 568-6327'},
        {'name': 'Arthur Anthony', 'email': 'arthur.anthony@theagencyre.com', 'phone': '(845) 242-2512'},
        {'name': 'Ashlie Roberson', 'email': 'ashlie@theagencyre.com', 'phone': '(917) 540-5578'},
        {'name': 'Ashlie Roberson', 'email': 'ashlie@theagencyre.com', 'phone': '(917) 540-5578'},
        {'name': 'Bailey Gladysz', 'email': 'bailey@theagencyre.com', 'phone': '(917) 970-2246'},
        {'name': 'Ben Falchi', 'email': 'ben.falchi@theagencyre.com', 'phone': '(917) 664-7144'},
        {'name': 'Benny Bardhecaj', 'email': 'benny.bardhecaj@theagencyre.com', 'phone': '(347) 939-4532'},
        {'name': 'Bethany Taufiq', 'email': 'bethany.taufiq@theagencyre.com', 'phone': '(347) 630-5970'},
        {'name': 'Betsy Whalen', 'email': 'betsy.whalen@theagencyre.com', 'phone': '(917) 297-1926'},
        {'name': 'Brandon Schultz', 'email': 'brandon.schultz@theagencyre.com', 'phone': '(319) 290-0677'},
        {'name': 'Brandon Marianne', 'email': 'brandon@theagencyre.com', 'phone': '(917) 521-9022'},
        {'name': 'Brigitte Pays', 'email': 'brigitte@theagencyre.com', 'phone': '(504) 432-3018'},
        {'name': 'Caitlin Daniele', 'email': 'caitlin.daniele@theagencyre.com', 'phone': '(917) 924-3355'},
        {'name': 'Caitlin Hartley', 'email': 'caitlin.hartley@theagencyre.com', 'phone': '(949) 244-2706'},
        {'name': 'Carson Alexander', 'email': 'carson@theagencyre.com', 'phone': '(512) 658-8664'},
        {'name': 'Cary Tamura', 'email': 'ct@theagencyre.com', 'phone': '(917) 604-0809'},
        {'name': 'Chase Safarowic', 'email': 'chase.safarowic@theagencyre.com', 'phone': '(914) 227-6418'},
        {'name': 'Chelsea Picken', 'email': 'chelsea.picken@theagencyre.com', 'phone': '(734) 904-0880'},
        {'name': 'Chloe Godin', 'email': 'chloe.godin@theagencyre.com', 'phone': '(646) 309-3356'},
        {'name': 'Chris Lee', 'email': 'chris.lee@theagencyre.com', 'phone': '(646) 285-3802'},
        {'name': 'Chris Toland', 'email': 'chris.toland@theagencyre.com', 'phone': '(347) 645-3976'},
        {'name': 'Chrisoula Papoutsakis', 'email': 'chrisoula@theagencyre.com', 'phone': '(917) 733-6832'},
        {'name': 'Ciara Wang', 'email': 'ciara.wang@theagencyre.com', 'phone': '(646) 249-6326'},
        {'name': 'Claudine Taylor', 'email': 'claudine.taylor@theagencyre.com', 'phone': '(980) 230-6745'},
        {'name': 'Corey Thomas', 'email': 'corey.thomas@theagencyre.com', 'phone': '(678) 684-7545'},
        {'name': 'Curtis Spencer', 'email': 'curtis.spencer@theagencyre.com', 'phone': '(646) 675-5610'},
        {'name': 'Dana Mayo', 'email': 'dana.mayo@theagencyre.com', 'phone': '(702) 373-9308'},
        {'name': 'Daniel Blatman', 'email': 'daniel.blatman@theagencyre.com', 'phone': '(917) 297-8575'},
        {'name': 'David Gibbs', 'email': 'david.gibbs@theagencyre.com', 'phone': '(908) 720-6004'},
        {'name': 'David Palermo', 'email': 'david.palermo@theagencyre.com', 'phone': '(302) 528-4331'},
        {'name': 'Don Hadel', 'email': 'don.hadel@theagencyre.com', 'phone': '(347) 273-3246'},
        {'name': 'Doris Lebron', 'email': 'doris.lebron@theagencyre.com', 'phone': '(917) 439-8531'},
        {'name': 'Dov Hoschander', 'email': 'dov.hoschander@theagencyre.com', 'phone': '(516) 567-3611'},
        {'name': 'Elena Smirnova', 'email': 'elena.smirnova@theagencyre.com', 'phone': '(646) 807-8311'},
        {'name': 'Elex Brown', 'email': 'elex.brown@theagencyre.com', 'phone': '(305) 399-4685'},
        {'name': 'Elina Brewer', 'email': 'elina.brewer@theagencyre.com', 'phone': '(347) 552-7373'},
        {'name': 'Elisa Seeger', 'email': 'elisa.seeger@theagencyre.com', 'phone': '(917) 750-9390'},
        {'name': 'Elizabeth Munn', 'email': 'elizabeth.munn@theagencyre.com', 'phone': '(929) 416-7828'},
        {'name': 'Emily Gordon-Jones', 'email': 'emily.gordon-jones@theagencyre.com', 'phone': '(717) 538-1459'},
        {'name': 'Erik Heitz', 'email': 'erik@theagencyre.com', 'phone': '(314) 960-7938'},
        {'name': 'Erika Maya', 'email': 'erika.maya@theagencyre.com', 'phone': '(347) 673-9795'},
        {'name': 'Erin Frisbie', 'email': 'erin.frisbie@theagencyre.com', 'phone': '(818) 445-4656'},
        {'name': 'Evan Roth', 'email': 'evan.roth@theagencyre.com', 'phone': '(516) 456-2590'},
        {'name': 'Everett Smith', 'email': 'everett.smith@theagencyre.com', 'phone': '(646) 653-4764'},
        {'name': 'Gabriel Minsky', 'email': 'gabriel.minsky@theagencyre.com', 'phone': '(917) 993-4481'},
        {'name': 'Gabriella Michin', 'email': 'gm@theagencyre.com', 'phone': '(347) 249-9249'},
        {'name': 'Gina Ko', 'email': 'gina@theagencyre.com', 'phone': '(917) 693-9975'},
        {'name': 'Ginny Nunez', 'email': 'ginny.nunez@theagencyre.com', 'phone': '(646) 864-4347'},
        {'name': 'Glenn Schwitter', 'email': 'glenn.schwitter@theagencyre.com', 'phone': '(860) 969-7577'},
        {'name': 'Heather Cella', 'email': 'heather.cella@theagencyre.com', 'phone': '(845) 641-7790'},
        {'name': 'Hila Peled', 'email': 'hila@theagencyre.com', 'phone': '(917) 651-4831'},
        {'name': 'Izabella Solarz', 'email': 'izabella.solarz@theagencyre.com', 'phone': '(917) 997-0577'},
        {'name': 'James Ward', 'email': 'james.ward@theagencyre.com', 'phone': '(917) 753-1106'},
        {'name': 'Jason Kadlec', 'email': 'jason.kadlec@theagencyre.com', 'phone': '(718) 490-2577'},
        {'name': 'Jason Prifold', 'email': 'j.prifold@theagencyre.com', 'phone': '(702) 684-1574'},
        {'name': 'Jeanine Royce', 'email': 'jeanine.royce@theagencyre.com', 'phone': '(914) 319-6049'},
        {'name': 'Jed Lewin,', 'email': 'Esq.', 'phone': 'jed.lewin@theagencyre.com (917) 609-0466'},
        {'name': 'Jeffrey Zicker', 'email': 'jeff.zicker@theagencyre.com', 'phone': '(702) 460-9490'},
        {'name': 'Jesse Scott', 'email': 'jesse.scott@theagencyre.com', 'phone': '(615) 438-3313'},
        {'name': 'Jill Steingart', 'email': 'jill@theagencyre.com', 'phone': '(845) 798-4323'},
        {'name': 'Jim Moorehead', 'email': 'jim@theagencyre.com', 'phone': '(347) 466-2064'},
        {'name': 'JJ Choi', 'email': 'jj@theagencyre.com', 'phone': '(917) 432-9018'},
        {'name': 'Joan Kagan', 'email': 'joan@theagencyre.com', 'phone': '(917) 992-9433'},
        {'name': 'John Antretter', 'email': 'john.antretter@theagencyre.com', 'phone': '(212) 658-0570'},
        {'name': 'Jon Amundsen', 'email': 'jon.amundsen@theagencyre.com', 'phone': '(917) 536-6672'},
        {'name': 'Josh Heyer', 'email': 'josh.heyer@theagencyre.com', 'phone': '(917) 970-2244'},
        {'name': 'Joshua Juneau', 'email': 'josh@theagencyre.com', 'phone': '(917) 442-1419'},
        {'name': 'Julian Shane', 'email': 'julian.shane@theagencyre.com', 'phone': '(347) 933-7566'},
        {'name': 'Juliana Hernandez', 'email': 'juliana@theagencyre.com', 'phone': '(917) 715-5592'},
        {'name': 'Julio Izquierdo', 'email': 'julio.izquierdo@theagencyre.com', 'phone': '(305) 607-3075'},
        {'name': 'Julius Mouser', 'email': 'julius.mouser@theagencyre.com', 'phone': '(267) 596-6341'},
        {'name': 'Kaci Beemon', 'email': 'kaci.beemon@theagencyre.com', 'phone': '(929) 482-1223'},
        {'name': 'Kaitlin Ruddy', 'email': 'kaitlin.ruddy@theagencyre.com', 'phone': '(773) 318-0838'},
        {'name': 'Karen Feldman', 'email': 'karen.feldman@theagencyre.com', 'phone': '(917) 747-7305'},
        {'name': 'Katarina Cribby', 'email': 'katarina.cribby@theagencyre.com', 'phone': '(425) 503-1673'},
        {'name': 'Katherine Brooke', 'email': 'katherine.brooke@theagencyre.com', 'phone': '(281) 222-1563'},
        {'name': 'Katie Haggerty', 'email': 'katie.haggerty@theagencyre.com', 'phone': '(312) 403-1109'},
        {'name': 'Kayla Klinge', 'email': 'kayla.klinge@theagencyre.com', 'phone': '(760) 525-5695'},
        {'name': 'Krysta Ciampaglia', 'email': 'krysta.ciampaglia@theagencyre.com', 'phone': '(917) 523-7585'},
        {'name': 'Kyle Ramdeen', 'email': 'kyle.ramdeen@theagencyre.com', 'phone': '(914) 299-5377'},
        {'name': 'Kyleen Smith', 'email': 'kyleen.smith@theagencyre.com', 'phone': '(307) 555-7890'},
        {'name': 'Laura Ann', 'email': 'Fiery', 'phone': 'Dowling laura.fiery@theagencyre.com (917) 749-6984'},
        {'name': 'Lauren Viviani', 'email': 'lauren.viviani@theagencyre.com', 'phone': '(917) 715-2593'},
        {'name': 'Lawrence Lee', 'email': 'lawrence@theagencyre.com', 'phone': '(917) 804-3385'},
        {'name': 'Leisa Aras', 'email': 'leisa@theagencyre.com', 'phone': '(917) 921-3758'},
        {'name': 'Lorraine Rigan', 'email': 'lorraine.rigan@theagencyre.com', 'phone': '(917) 905-4345'},
        {'name': 'Luke Hoback', 'email': 'luke.hoback@theagencyre.com', 'phone': '(917) 994-8897'},
        {'name': 'Madeleine Auffenberg', 'email': 'madeleine.auffenberg@theagencyre.com', 'phone': '(646) 991-5915'},
        {'name': 'Marcus Malone', 'email': 'marcus.malone@theagencyre.com', 'phone': '(407) 233-7903'},
        {'name': 'Marnie Eden', 'email': 'marnie.eden@theagencyre.com', 'phone': '(917) 710-6603'},
        {'name': 'Marsha Essman', 'email': 'marsha@theagencyre.com', 'phone': '(917) 576-4151'},
        {'name': 'Martha Brophy', 'email': 'martha.brophy@theagencyre.com', 'phone': '(917) 535-4359'},
        {'name': 'Maureen Klein', 'email': 'maureen.klein@theagencyre.com', 'phone': '(606) 465-0863'},
        {'name': 'Maurice Singer', 'email': 'maurice@theagencyre.com', 'phone': '(917) 209-8487'},
        {'name': 'Melissa Bemis', 'email': 'melissa.bemis@theagencyre.com', 'phone': '(908) 812-6831'},
        {'name': 'Melissa Gaccione', 'email': 'melissa.gaccione@theagencyre.com', 'phone': '(850) 830-5164'},
        {'name': 'Michael Biryla', 'email': 'mikeb@theagencyre.com', 'phone': '(646) 496-2174'},
        {'name': 'Michael Popovsky', 'email': 'michaelp@theagencyre.com', 'phone': '(201) 638-2362'},
        {'name': 'Michael Simmon-Pappadakos', 'email': 'michael.sp@theagencyre.com', 'phone': '(646) 789-3142'},
        {'name': 'Michael Zaccaria', 'email': 'michael.zaccaria@theagencyre.com', 'phone': '(917) 207-4070'},
        {'name': 'Michelle Amodeo', 'email': 'michelle.amodeo@theagencyre.com', 'phone': '(610) 547-5309'},
        {'name': 'Michelle Siegel', 'email': 'michelle.siegel@theagencyre.com', 'phone': '(646) 398-0411'},
        {'name': 'Michelle Wu', 'email': 'michelle.wu@theagencyre.com', 'phone': '(646) 341-7595'},
        {'name': 'Mike Fabbri', 'email': 'mike.fabbri@theagencyre.com', 'phone': '(917) 226-6132'},
        {'name': 'Molly Townsend', 'email': 'molly.townsend@theagencyre.com', 'phone': '(917) 658-7282'},
        {'name': 'Monica Park', 'email': 'monica.park@theagencyre.com', 'phone': '(347) 633-1145'},
        {'name': 'Nadeem Kazi', 'email': 'nadeem.kazi@theagencyre.com', 'phone': '(718) 795-8082'},
        {'name': 'Nadiya Hrytchuk', 'email': 'nadiya.hrytchuk@theagencyre.com', 'phone': '(917) 971-4466'},
        {'name': 'Nicole Dreyfuss', 'email': 'nicole.dreyfuss@theagencyre.com', 'phone': '(646) 295-4443'},
        {'name': 'Noel Borbon', 'email': 'noel@theagencyre.com', 'phone': '(347) 264-1515'},
        {'name': 'Paul LeMarc', 'email': 'Brown', 'phone': 'paul.lemarc@theagencyre.com (917) 375-2932'},
        {'name': 'Pedro Crespo', 'email': 'pedro@theagencyre.com', 'phone': '(646) 338-9986'},
        {'name': 'Penelope Stipanovich', 'email': 'penelope.s@theagencyre.com', 'phone': '(212) 518-6233 License: DRE #2024827'},
        {'name': 'Peta Couzens', 'email': 'peta@theagencyre.com', 'phone': '(917) 794-0055'},
        {'name': 'Philip Andriotti', 'email': 'philip.andriotti@theagencyre.com', 'phone': '(516) 637-0028'},
        {'name': 'Rachel Epstein', 'email': 'rachel.epstein@theagencyre.com', 'phone': '(718) 747-4883'},
        {'name': 'Rachel Zack', 'email': 'rachel.zack@theagencyre.com', 'phone': '(929) 620-8232'},
        {'name': 'Rae McKee', 'email': 'rae.mckee@theagencyre.com', 'phone': '(605) 593-2513'},
        {'name': 'Rebecca Brooksher', 'email': 'rebecca.brooksher@theagencyre.com', 'phone': '(646) 269-8232'},
        {'name': 'Rodica Balan', 'email': 'rodica.balan@theagencyre.com', 'phone': '(347) 589-5664'},
        {'name': 'Roman Trevino', 'email': 'roman.trevino@theagencyre.com', 'phone': '(713) 261-9289'},
        {'name': 'Ryan Watanabe', 'email': 'ryan.watanabe@theagencyre.com', 'phone': '(917) 318-3225'},
        {'name': 'Samuel Okine', 'email': 'samuel.okine@theagencyre.com', 'phone': '(917) 736-5427'},
        {'name': 'Sandy Levering', 'email': 'sandy.levering@theagencyre.com', 'phone': '(917) 576-9485'},
        {'name': 'Sara Jimenez-Curtola', 'email': 'sara.curtola@theagencyre.com', 'phone': '(917) 261-3745'},
        {'name': 'Sarna Roy', 'email': 'sarna.roy@theagencyre.com', 'phone': '(347) 400-1903'},
        {'name': 'Sean Brewer', 'email': 'sean.brewer@theagencyre.com', 'phone': '(785) 550-9251'},
        {'name': 'Sergio Pasquariello', 'email': 'sergio.pasquariello@theagencyre.com', 'phone': '(310) 986-5432'},
        {'name': 'Shane Boyle', 'email': 'shane.boyle@theagencyre.com', 'phone': '(917) 250-0290'},
        {'name': 'Shawn Fagan', 'email': 'shawn.fagan@theagencyre.com', 'phone': '(347) 262-5970'},
        {'name': 'Shelly Place', 'email': 'shelly@theagencyre.com', 'phone': '(650) 862-0377'},
        {'name': 'Socratis Georgiou', 'email': 'socratis.georgiou@theagencyre.com', 'phone': '(646) 250-1990'},
        {'name': 'Sorel Roget', 'email': 'sorel@theagencyre.com', 'phone': '(917) 355-7599'},
        {'name': 'Spencer Nauman', 'email': 'spencer.nauman@theagencyre.com', 'phone': '(319) 541-8954'},
        {'name': 'Stefan Vujovic', 'email': 'stefan.vujovic@theagencyre.com', 'phone': '(646) 881-0730'},
        {'name': 'Stephanie Moon', 'email': 'stephanie.moon@theagencyre.com', 'phone': '(917) 553-4139'},
        {'name': 'Stephen Setzer', 'email': 'stephen.setzer@theagencyre.com', 'phone': '(212) 518-3128'},
        {'name': 'Steven Kopstein', 'email': 'steven@theagencyre.com', 'phone': '(917) 414-3653'},
        {'name': 'Susan Duncan', 'email': 'susan.duncan@theagencyre.com', 'phone': '(310) 701-3073'},
        {'name': 'Tami Kurtz', 'email': 'tami@theagencyre.com', 'phone': '(917) 207-8960'},
        {'name': 'Teresa Staiano', 'email': 'teresa@theagencyre.com', 'phone': '(917) 596-5538'},
        {'name': 'Theresa Persaud', 'email': 'theresa.persaud@theagencyre.com', 'phone': '(917) 862-6892'},
        {'name': 'Timothy Ford', 'email': 'timothy.ford@theagencyre.com', 'phone': '(631) 404-8731'},
        {'name': 'Toni Geyelin', 'email': 'toni.geyelin@theagencyre.com', 'phone': '(917) 226-2290'},
        {'name': 'Tracy Yuan', 'email': 'tracy.yuan@theagencyre.com', 'phone': '(631) 816-0141'},
        {'name': 'Tyler Whitman', 'email': 'tyler@theagencyre.com', 'phone': '(917) 565-5166'},
        {'name': 'Wendy Lichtenberg', 'email': 'wendy.lichtenberg@theagencyre.com', 'phone': '(516) 639-9397'},
        {'name': 'Will Apicella', 'email': 'will.apicella@theagencyre.com', 'phone': '(862) 812-7893'},
        {'name': 'Will Ortman', 'email': 'will.ortman@theagencyre.com', 'phone': '(609) 651-6649'},
        {'name': 'Yanni Kiskini', 'email': 'yanni.kiskini@theagencyre.com', 'phone': '(212) 444-7876'},
        {'name': 'Zachary Brown', 'email': 'zachary.brown@theagencyre.com', 'phone': '(610) 603-6821'},
        {'name': 'Zachary Gillespie', 'email': 'zachary.gillespie@theagencyre.com', 'phone': '(646) 951-3779'},
        {'name': 'Zachary Scott', 'email': 'zed@theagencyre.com', 'phone': '(917) 480-9294'},

    ]


# Create a DataFrame from the data
df = pd.DataFrame(data)

# Drop rows with undefined values (NaN or empty strings)
df = df.dropna(subset=['name', 'email', 'phone'])

# Specify the output CSV file path
output_csv = 'cleaned_data.csv'

# Save the cleaned DataFrame to a CSV file
df.to_csv(output_csv, index=False)

print(f"Cleaned data saved to '{output_csv}'")
